from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import Optional, List
from sqlalchemy.orm import Session
from app.models.database import get_db
from app.models.models import Message
from app.services.embedding_service import embedding_service
from app.services.llm_service import llm_service

router = APIRouter()

class ChatRequest(BaseModel):
    question: str
    document_id: Optional[int] = None

class ChatResponse(BaseModel):
    answer: str
    sources: list[str]

class MessageResponse(BaseModel):
    id: int
    role: str
    content: str
    
    class Config:
        orm_mode = True

@router.get("/history/{document_id}", response_model=List[MessageResponse])
def get_chat_history(document_id: int, db: Session = Depends(get_db)):
    return db.query(Message).filter(Message.document_id == document_id).order_by(Message.created_at.asc()).all()

from app.api.routes.auth import get_current_user

@router.post("/", response_model=ChatResponse)
def ask_question(request: ChatRequest, db: Session = Depends(get_db), current_user: int = Depends(get_current_user)):
    relevant_chunks = []
    sources = []
    history = []
    
    # Record permanent activity log for streak
    from app.models.models import ActivityLog
    import datetime
    today_str = datetime.datetime.now().strftime("%Y-%m-%d")
    existing_log = db.query(ActivityLog).filter(
        ActivityLog.user_id == current_user,
        ActivityLog.date_string == today_str
    ).first()
    
    if not existing_log:
        db.add(ActivityLog(user_id=current_user, date_string=today_str))
        db.commit()

    # If a document is provided, fetch history and search for relevant context
    if request.document_id:
        # Save user message
        user_msg = Message(document_id=request.document_id, role="user", content=request.question)
        db.add(user_msg)
        db.commit()

        # Fetch last 5 messages for memory
        past_msgs = db.query(Message).filter(Message.document_id == request.document_id).order_by(Message.created_at.desc()).limit(5).all()
        # Reverse to chronological order
        past_msgs.reverse()
        history = [{"role": msg.role, "content": msg.content} for msg in past_msgs[:-1]] # exclude the one we just added

        # Search vector DB
        results = embedding_service.search(request.question, n_results=3, document_id=request.document_id)
        if results:
            relevant_chunks = results
            for res in results:
                sources.append(res['text'][:100] + "...") 

    # Pass history, chunks, and question to the LLM
    answer = llm_service.generate_response(request.question, context_chunks=relevant_chunks, history=history)
    
    if request.document_id:
        # Save assistant message
        asst_msg = Message(document_id=request.document_id, role="assistant", content=answer)
        db.add(asst_msg)
        db.commit()

    return ChatResponse(answer=answer, sources=sources)

import json
from fastapi import HTTPException
from app.models.models import Document
from app.api.routes.auth import get_current_user

@router.post("/quiz/{document_id}")
def generate_quiz(document_id: int, db: Session = Depends(get_db), current_user: int = Depends(get_current_user)):
    doc = db.query(Document).filter(Document.id == document_id, Document.owner_id == current_user).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
        
    text_to_use = doc.summary if doc.summary else doc.original_text
    
    try:
        raw_response = llm_service.generate_quiz(text_to_use)
        # Clean up any potential markdown code blocks returned by the model
        if raw_response.startswith("```json"):
            raw_response = raw_response[7:-3]
        elif raw_response.startswith("```"):
            raw_response = raw_response[3:-3]
            
        quiz_data = json.loads(raw_response.strip())
        return {"quiz": quiz_data}
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Failed to parse quiz generated by AI")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
